# Some distributed configs
data_dir: '/mnt/dog/bran/CoW_MRI/imagesTr_resampled'
sampling_steps:
  - 2500
  - 5000
  - 5000
video_save_path: "distributed_experiments/images"
checkpoint_path: "distributed_experiments/"
batch_size: 2
max_iterations:
  - 20000
  - 50000
  - 150000
num_frames: 128
num_workers: 16
device: "cuda"
train_unet_number: 1
unet_1_checkpoint: "trained_video_1.pt"
unet_2_checkpoint: "trained_video_2.pt"
unet_3_checkpoint: "trained_video_3.pt"
load_prev_checkpoint: True
resume: False  # Resume training
# Some wandb configurations
wandb:
  project: "video_diff"
  mode: "online"
